[package]
name = "Michael-F-bryan/wcgi-rust-template"
version = "0.1.0"
description = "A template for WCGI applications"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wasmerio/wcgi-rust-template"

[[module]]
name = "server"
source = "target/wasm32-wasi/release/wcgi-rust-template.wasm"
abi = "wasi"

[[command]]
name = "server"
runner = "https://webc.org/runner/wcgi"
module = "wcgi"
annotations = { wcgi = { dialect = "rfc-3875" } }
